language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.6
      env: TOXENV=lint
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=docs
    - python: pypy
      env: TOXENV=pypy

install:
  - pip install tox codecov

script:
  - tox

after_success:
  - codecov --env TRAVIS_OS_NAME,TOXENV

notifications:
  irc:
    channels:
      - "irc.freenode.org#pypa-dev"
    use_notice: true
    skip_join: true
